mqtt:
  broker: 
  client_id: 
  client_password: 
  environment_topic: 
  device_topic: 

gin:
  ip: 127.0.0.1
  port: 8081
  jwt_secret: 

server:
  path: 

mysql:
  dsn: 

redis:
  addr: 
  password: ""
  db: 0

qq:
  from: 
  password: 

room_mapping:
  room1: enviroment1
  room2: enviroment2

filepath: path_to_ok.png
filepath2: path_to_damie.png